<!DOCTYPE html>
<html lang="pt-BR"><head>
<script src="aula_lgpd_files/libs/clipboard/clipboard.min.js"></script>
<script src="aula_lgpd_files/libs/quarto-html/tabby.min.js"></script>
<script src="aula_lgpd_files/libs/quarto-html/popper.min.js"></script>
<script src="aula_lgpd_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="aula_lgpd_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="aula_lgpd_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="aula_lgpd_files/libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.36">

  <meta name="author" content="Aula elaborada com base nos guias orientativos da ANPD e no texto legal">
  <meta name="dcterms.date" content="2026-04-29">
  <title>Lei Geral de Proteção de Dados Pessoais (LGPD)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="aula_lgpd_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="aula_lgpd_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="aula_lgpd_files/libs/revealjs/dist/theme/quarto-2abc1c5b7b5c7eecd6137558e106e4c3.css">
  <link href="aula_lgpd_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="aula_lgpd_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="aula_lgpd_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="aula_lgpd_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="aula_lgpd_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="aula_lgpd_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lei Geral de Proteção de Dados Pessoais (LGPD)</h1>
  <p class="subtitle">Lei nº 13.709/2018 — fundamentos, estrutura e aplicação prática</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Aula elaborada com base nos guias orientativos da ANPD e no texto legal 
</div>
</div>
</div>

  <p class="date">2026-04-29</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Roteiro da aula</h2>
<ul>
<li><a href="#/parte-i-estrutura-e-âmbito-de-aplicação-da-lgpd" id="/toc-parte-i-estrutura-e-âmbito-de-aplicação-da-lgpd">Parte I — Estrutura e âmbito de aplicação da LGPD</a></li>
<li><a href="#/parte-ii-princípios-gerais-do-tratamento" id="/toc-parte-ii-princípios-gerais-do-tratamento">Parte II — Princípios gerais do tratamento</a></li>
<li><a href="#/parte-iii-bases-legais-para-o-tratamento-de-dados" id="/toc-parte-iii-bases-legais-para-o-tratamento-de-dados">Parte III — Bases legais para o tratamento de dados</a></li>
<li><a href="#/parte-iv-agentes-de-tratamento-e-responsabilidades" id="/toc-parte-iv-agentes-de-tratamento-e-responsabilidades">Parte IV — Agentes de tratamento e responsabilidades</a></li>
<li><a href="#/parte-v-direitos-do-titular" id="/toc-parte-v-direitos-do-titular">Parte V — Direitos do titular</a></li>
<li><a href="#/parte-vi-segurança-incidentes-e-boas-práticas" id="/toc-parte-vi-segurança-incidentes-e-boas-práticas">Parte VI — Segurança, incidentes e boas práticas</a></li>
<li><a href="#/parte-vii-transferência-internacional-de-dados" id="/toc-parte-vii-transferência-internacional-de-dados">Parte VII — Transferência internacional de dados</a></li>
<li><a href="#/parte-viii-anpd-e-o-sistema-de-fiscalização" id="/toc-parte-viii-anpd-e-o-sistema-de-fiscalização">Parte VIII — ANPD e o sistema de fiscalização</a></li>
<li><a href="#/parte-ix-tratamento-de-dados-pelo-poder-público" id="/toc-parte-ix-tratamento-de-dados-pelo-poder-público">Parte IX — Tratamento de dados pelo poder público</a></li>
<li><a href="#/parte-x-programa-de-governança-em-privacidade" id="/toc-parte-x-programa-de-governança-em-privacidade">Parte X — Programa de governança em privacidade</a></li>
<li><a href="#/parte-xi-casos-práticos-e-situações-cotidianas" id="/toc-parte-xi-casos-práticos-e-situações-cotidianas">Parte XI — Casos práticos e situações cotidianas</a></li>
<li><a href="#/conclusão" id="/toc-conclusão">Conclusão</a></li>
</ul>
</nav>
</section>
<section id="por-que-proteger-dados-pessoais" class="slide level2">
<h2>Por que proteger dados pessoais?</h2>
<p>Vivemos em um mundo onde bilhões de operações digitais ocorrem a cada segundo. A cada clique, compra, cadastro ou acesso a um serviço público, dados pessoais são gerados, armazenados e processados.</p>
<div class="fragment">
<p>Sem regras claras, esse fluxo pode:</p>
<ul>
<li>alimentar discriminação (crédito, emprego, saúde)</li>
<li>violar a privacidade e a dignidade das pessoas</li>
<li>criar assimetrias de poder entre empresas e cidadãos</li>
<li>expor indivíduos a fraudes, perseguições e danos morais</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p>A proteção de dados pessoais é, antes de tudo, uma questão de <strong>direitos fundamentais</strong>.</p>
</blockquote>
</div>
</section>
<section id="contexto-histórico-e-internacional" class="slide level2">
<h2>Contexto histórico e internacional</h2>
<p><strong>Décadas de 1970–1990:</strong> primeiras leis nacionais de proteção de dados na Europa (Suécia, Alemanha, França).</p>
<p><strong>1995:</strong> Diretiva Europeia 95/46/CE — marco do modelo europeu de proteção de dados.</p>
<p><strong>2016/2018:</strong> Regulamento Geral de Proteção de Dados da União Europeia (<strong>GDPR</strong>) — inspiração direta para a LGPD.</p>
<p><strong>2018:</strong> sanção da <strong>Lei nº 13.709</strong> — Lei Geral de Proteção de Dados Pessoais (<strong>LGPD</strong>).</p>
<p><strong>2020:</strong> entrada em vigor da LGPD (setembro de 2020); sanções administrativas a partir de agosto de 2021.</p>
<p><strong>2022:</strong> a <strong>Emenda Constitucional nº 115</strong> elevou a proteção de dados pessoais ao rol dos direitos e garantias fundamentais (art. 5º, LXXIX, da CF/88).</p>
</section>
<section id="a-proteção-de-dados-como-direito-fundamental" class="slide level2">
<h2>A proteção de dados como direito fundamental</h2>
<p>Com a EC nº 115/2022, o art. 5º, LXXIX da Constituição Federal passou a prever expressamente:</p>
<blockquote>
<p><em>“é assegurado, nos termos da lei, o direito à proteção dos dados pessoais, inclusive nos meios digitais.”</em></p>
</blockquote>
<div class="fragment">
<p>Isso tem consequências práticas relevantes:</p>
<ul>
<li>integra o núcleo dos direitos fundamentais, com proteção constitucional reforçada</li>
<li>reforça a vinculação de toda a administração pública às normas da LGPD</li>
<li>serve de parâmetro de interpretação para todo o ordenamento infraconstitucional</li>
</ul>
</div>
</section>
<section>
<section id="parte-i-estrutura-e-âmbito-de-aplicação-da-lgpd" class="title-slide slide level1 center">
<h1>Parte I — Estrutura e âmbito de aplicação da LGPD</h1>

</section>
<section id="o-que-é-a-lgpd" class="slide level2">
<h2>O que é a LGPD?</h2>
<p>A <strong>Lei nº 13.709, de 14 de agosto de 2018</strong>, dispõe sobre o tratamento de dados pessoais, inclusive em meio digital, por pessoa natural ou jurídica de direito público ou privado, com o objetivo de proteger os direitos fundamentais de liberdade e de privacidade e o livre desenvolvimento da personalidade da pessoa natural (art. 1º).</p>
<div class="fragment">
<p>A lei foi alterada pela <strong>Lei nº 13.853/2019</strong>, que, entre outras mudanças:</p>
<ul>
<li>criou a <strong>ANPD</strong> — então “Autoridade Nacional de Proteção de Dados”, transformada em agência reguladora pela <strong>Lei nº 15.352/2026</strong></li>
<li>instituiu o <strong>CNPD</strong> (Conselho Nacional de Proteção de Dados Pessoais e da Privacidade)</li>
<li>ajustou prazos e definições</li>
</ul>
</div>
</section>
<section id="âmbito-de-aplicação-art.-3º" class="slide level2">
<h2>Âmbito de aplicação (art. 3º)</h2>
<p>A LGPD aplica-se a qualquer operação de tratamento realizada:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Critério</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Território</strong></td>
<td>operação realizada no Brasil</td>
</tr>
<tr class="even">
<td><strong>Oferta</strong></td>
<td>atividade voltada à oferta de bens ou serviços a indivíduos no Brasil</td>
</tr>
<tr class="odd">
<td><strong>Coleta</strong></td>
<td>dados coletados em território nacional</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>A aplicação <strong>independe</strong> do meio, da sede da empresa ou da localização dos dados — inclusive no exterior.</p>
</div>
</section>
<section id="hipóteses-de-não-aplicação-art.-4º" class="slide level2">
<h2>Hipóteses de <strong>não</strong> aplicação (art. 4º)</h2>
<p>A LGPD <strong>não</strong> se aplica ao tratamento de dados pessoais realizado:</p>
<ul>
<li>por pessoa natural para fins exclusivamente particulares e não econômicos</li>
<li>para fins exclusivamente jornalísticos, artísticos ou acadêmicos (com ressalvas)</li>
<li>para fins exclusivos de segurança pública, defesa nacional, segurança do Estado e atividades de investigação e repressão de infrações penais</li>
<li>proveniente de fora do território nacional e que não seja objeto de comunicação com agentes de tratamento brasileiros, nem objeto de transferência internacional</li>
</ul>
<blockquote>
<p>⚠️ As exceções são interpretadas de forma <strong>restritiva</strong>.</p>
</blockquote>
</section>
<section id="conceitos-chave-dado-pessoal-e-dado-sensível" class="slide level2">
<h2>Conceitos-chave: dado pessoal e dado sensível</h2>
<p><strong>Dado pessoal</strong> (art. 5º, I): &gt; Informação relacionada a <strong>pessoa natural identificada ou identificável</strong>.</p>
<div class="fragment">
<p>Exemplos: nome, CPF, e-mail, endereço IP, geolocalização, número de telefone, cookie de identificação.</p>
</div>
<div class="fragment">
<p><strong>Dado pessoal sensível</strong> (art. 5º, II): &gt; dado sobre origem racial ou étnica, convicção religiosa, opinião política, filiação sindical ou a organização religiosa, filosófica ou política; dado referente à saúde ou vida sexual; dado genético ou biométrico, quando vinculado a uma pessoa natural.</p>
</div>
<div class="fragment">
<blockquote>
<p>⚠️ Dados sensíveis recebem <strong>proteção reforçada</strong> — regime jurídico especial (art. 11).</p>
</blockquote>
</div>
</section>
<section id="outros-conceitos-essenciais-art.-5º" class="slide level2">
<h2>Outros conceitos essenciais (art. 5º)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Termo</th>
<th>Definição legal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Tratamento</strong></td>
<td>toda operação realizada com dados: coleta, produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação, controle, modificação, comunicação, transferência, difusão ou extração</td>
</tr>
<tr class="even">
<td><strong>Controlador</strong></td>
<td>pessoa natural ou jurídica que toma as decisões sobre o tratamento</td>
</tr>
<tr class="odd">
<td><strong>Operador</strong></td>
<td>pessoa natural ou jurídica que realiza o tratamento em nome do controlador</td>
</tr>
<tr class="even">
<td><strong>Encarregado (DPO)</strong></td>
<td>pessoa indicada pelo controlador para atuar como canal de comunicação</td>
</tr>
<tr class="odd">
<td><strong>Titular</strong></td>
<td>pessoa natural a quem se referem os dados tratados</td>
</tr>
<tr class="even">
<td><strong>Anonimização</strong></td>
<td>processo pelo qual um dado perde, de forma irreversível, a possibilidade de associação a um indivíduo</td>
</tr>
</tbody>
</table>
</section>
<section id="dado-anonimizado-vs.-dado-pseudonimizado" class="slide level2">
<h2>Dado anonimizado vs.&nbsp;dado pseudonimizado</h2>
<p><strong>Dado anonimizado</strong> (art. 5º, III): dado relativo ao titular que não pode ser identificado, considerando a utilização de meios técnicos razoáveis e disponíveis na ocasião do tratamento. Não é dado pessoal para fins da LGPD.</p>
<div class="fragment">
<p><strong>Dado pseudonimizado</strong> (art. 5º, XIII): tratamento por meio do qual um dado perde a possibilidade de associação direta a um indivíduo, senão pelo uso de informação adicional mantida separadamente pelo controlador em ambiente controlado e seguro. <strong>Continua sendo dado pessoal</strong>.</p>
</div>
<div class="fragment">
<blockquote>
<p>A distinção é crucial: pseudonimização reduz riscos, mas não retira a incidência da LGPD. Anonimização genuína exclui a aplicação da lei.</p>
</blockquote>
</div>
</section></section>
<section>
<section id="parte-ii-princípios-gerais-do-tratamento" class="title-slide slide level1 center">
<h1>Parte II — Princípios gerais do tratamento</h1>

</section>
<section id="os-dez-princípios-do-art.-6º" class="slide level2">
<h2>Os dez princípios do art. 6º</h2>
<p>A LGPD estabelece dez princípios que regem <strong>toda e qualquer</strong> atividade de tratamento de dados. São mandamentos normativos, não meras recomendações.</p>
<div class="fragment">
<blockquote>
<p><em>“As atividades de tratamento de dados pessoais deverão observar a boa-fé e os seguintes princípios…”</em> (art. 6º, caput)</p>
</blockquote>
</div>
</section>
<section id="princípio-da-finalidade" class="slide level2">
<h2>Princípio da finalidade</h2>
<p><strong>Art. 6º, I</strong> — realização do tratamento para propósitos <strong>legítimos, específicos, explícitos e informados</strong> ao titular, sem possibilidade de tratamento posterior de forma incompatível com essas finalidades.</p>
<div class="fragment">
<p><strong>Na prática:</strong> ao coletar um e-mail para enviar uma nota fiscal, a empresa não pode usá-lo, posteriormente, para campanhas de marketing sem base legal independente. A finalidade original limita o uso futuro dos dados.</p>
</div>
</section>
<section id="princípio-da-adequação" class="slide level2">
<h2>Princípio da adequação</h2>
<p><strong>Art. 6º, II</strong> — compatibilidade do tratamento com as finalidades informadas ao titular, de acordo com o contexto do tratamento.</p>
<div class="fragment">
<p><strong>Na prática:</strong> os dados coletados devem ser adequados ao contexto em que foram fornecidos. Dados de saúde fornecidos para atendimento médico não podem ser usados para fins comerciais, ainda que exista consentimento genérico.</p>
</div>
</section>
<section id="princípio-da-necessidade" class="slide level2">
<h2>Princípio da necessidade</h2>
<p><strong>Art. 6º, III</strong> — limitação do tratamento ao <strong>mínimo necessário</strong> para a realização de suas finalidades, com abrangência dos dados pertinentes, proporcionais e não excessivos em relação às finalidades do tratamento de dados.</p>
<div class="fragment">
<p><strong>Na prática:</strong> se para cadastrar um usuário basta nome e e-mail, não há justificativa para coletar data de nascimento, CPF e endereço — a não ser que exista finalidade específica e base legal para cada campo adicional.</p>
</div>
</section>
<section id="princípio-do-livre-acesso" class="slide level2">
<h2>Princípio do livre acesso</h2>
<p><strong>Art. 6º, IV</strong> — garantia, aos titulares, de consulta facilitada e gratuita sobre a forma e a duração do tratamento, bem como sobre a integralidade de seus dados pessoais.</p>
<div class="fragment">
<p><strong>Na prática:</strong> o titular deve poder saber, a qualquer momento e sem custo, quais dados a empresa possui sobre ele, por que os trata e por quanto tempo os manterá.</p>
</div>
</section>
<section id="princípio-da-qualidade-dos-dados" class="slide level2">
<h2>Princípio da qualidade dos dados</h2>
<p><strong>Art. 6º, V</strong> — garantia, aos titulares, de exatidão, clareza, relevância e atualização dos dados, de acordo com a necessidade e para o cumprimento da finalidade de seu tratamento.</p>
<div class="fragment">
<p><strong>Na prática:</strong> manter bases de dados desatualizadas, com informações incorretas ou irrelevantes, configura violação desse princípio — e pode gerar responsabilidade quando causa danos ao titular.</p>
</div>
</section>
<section id="princípio-da-transparência" class="slide level2">
<h2>Princípio da transparência</h2>
<p><strong>Art. 6º, VI</strong> — garantia, aos titulares, de informações claras, precisas e facilmente acessíveis sobre a realização do tratamento e os respectivos agentes de tratamento, observados os segredos comercial e industrial.</p>
<div class="fragment">
<p><strong>Na prática:</strong> políticas de privacidade obscuras, escritas em linguagem técnica e inacessível, violam esse princípio. A transparência exige linguagem clara e acessível ao público-alvo.</p>
</div>
</section>
<section id="princípio-da-segurança" class="slide level2">
<h2>Princípio da segurança</h2>
<p><strong>Art. 6º, VII</strong> — utilização de medidas técnicas e administrativas aptas a proteger os dados pessoais de acessos não autorizados e de situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou difusão.</p>
<div class="fragment">
<p><strong>Na prática:</strong> controles de acesso, criptografia, registros de auditoria (logs), planos de resposta a incidentes e treinamentos de equipe são exemplos de medidas de segurança exigidas.</p>
</div>
</section>
<section id="princípio-da-prevenção" class="slide level2">
<h2>Princípio da prevenção</h2>
<p><strong>Art. 6º, VIII</strong> — adoção de medidas para prevenir a ocorrência de danos em virtude do tratamento de dados pessoais.</p>
<div class="fragment">
<p><strong>Na prática:</strong> não basta reagir a incidentes — é necessário agir preventivamente, avaliando riscos antes de iniciar um novo tratamento. Aqui entra o conceito de <strong>privacy by design</strong> (privacidade desde a concepção).</p>
</div>
</section>
<section id="princípio-da-não-discriminação" class="slide level2">
<h2>Princípio da não discriminação</h2>
<p><strong>Art. 6º, IX</strong> — impossibilidade de realização do tratamento para fins discriminatórios ilícitos ou abusivos.</p>
<div class="fragment">
<p><strong>Na prática:</strong> usar dados para negar crédito, emprego ou serviços com base em origem étnica, religião, opinião política ou outros dados sensíveis, sem base legal adequada, é expressamente vedado.</p>
</div>
</section>
<section id="princípio-da-responsabilização-e-prestação-de-contas" class="slide level2">
<h2>Princípio da responsabilização e prestação de contas</h2>
<p><strong>Art. 6º, X</strong> — demonstração, pelo agente, da adoção de medidas eficazes e capazes de comprovar a observância e o cumprimento das normas de proteção de dados pessoais e, inclusive, da eficácia dessas medidas.</p>
<div class="fragment">
<p><strong>Na prática:</strong> o ônus de demonstrar conformidade é do <strong>agente de tratamento</strong>, não do titular ou da ANPD. Documentação, políticas internas, treinamentos e registros de atividades são fundamentais para demonstrar <em>accountability</em>.</p>
</div>
</section></section>
<section>
<section id="parte-iii-bases-legais-para-o-tratamento-de-dados" class="title-slide slide level1 center">
<h1>Parte III — Bases legais para o tratamento de dados</h1>

</section>
<section id="o-que-são-bases-legais" class="slide level2">
<h2>O que são bases legais?</h2>
<p>A LGPD adota o modelo do <strong>numerus clausus</strong>: o tratamento de dados pessoais só é lícito se fundamentado em <strong>uma das hipóteses expressamente previstas</strong> na lei.</p>
<div class="fragment">
<p>Isso significa que:</p>
<ul>
<li>não existe tratamento lícito “por padrão”</li>
<li>a empresa deve identificar <strong>qual</strong> base legal justifica <strong>cada</strong> operação de tratamento</li>
<li>bases legais diferentes têm requisitos e consequências diferentes</li>
</ul>
</div>
</section>
<section id="as-dez-bases-legais-para-dados-comuns-art.-7º" class="slide level2">
<h2>As dez bases legais para dados comuns (art. 7º)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Base legal</th>
<th>Síntese</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>I</td>
<td><strong>Consentimento</strong></td>
<td>manifestação livre, informada, inequívoca e específica</td>
</tr>
<tr class="even">
<td>II</td>
<td><strong>Obrigação legal/regulatória</strong></td>
<td>cumprimento de norma jurídica pelo controlador</td>
</tr>
<tr class="odd">
<td>III</td>
<td><strong>Políticas públicas</strong></td>
<td>execução pela administração pública</td>
</tr>
<tr class="even">
<td>IV</td>
<td><strong>Pesquisa</strong></td>
<td>estudos por órgão de pesquisa, com anonimização sempre que possível</td>
</tr>
<tr class="odd">
<td>V</td>
<td><strong>Execução de contrato</strong></td>
<td>necessário para contrato do qual o titular é parte</td>
</tr>
<tr class="even">
<td>VI</td>
<td><strong>Exercício regular de direitos</strong></td>
<td>processos judicial, administrativo ou arbitral</td>
</tr>
<tr class="odd">
<td>VII</td>
<td><strong>Proteção da vida</strong></td>
<td>proteção da vida ou incolumidade física</td>
</tr>
<tr class="even">
<td>VIII</td>
<td><strong>Tutela da saúde</strong></td>
<td>por profissionais de saúde ou autoridades sanitárias</td>
</tr>
<tr class="odd">
<td>IX</td>
<td><strong>Interesse legítimo</strong></td>
<td>exceto quando prevalecerem direitos e liberdades fundamentais do titular</td>
</tr>
<tr class="even">
<td>X</td>
<td><strong>Proteção ao crédito</strong></td>
<td>conforme legislação pertinente</td>
</tr>
</tbody>
</table>
</section>
<section id="consentimento-requisitos-e-limites" class="slide level2">
<h2>Consentimento — requisitos e limites</h2>
<p>O consentimento (art. 5º, XII) deve ser:</p>
<ul>
<li><strong>livre</strong> — sem coerção ou condicionamento indevido</li>
<li><strong>informado</strong> — o titular deve saber o que está consentindo</li>
<li><strong>inequívoco</strong> — não admite presunção nem silêncio como anuência</li>
<li><strong>específico</strong> — para finalidades determinadas</li>
</ul>
<div class="fragment">
<p><strong>Revogação (art. 8º, §5º):</strong> o titular pode revogar o consentimento a qualquer momento, mediante manifestação expressa, por procedimento gratuito e facilitado.</p>
</div>
<div class="fragment">
<blockquote>
<p>⚠️ Consentimento <strong>não</strong> é a única nem a principal base legal. Utilizá-lo como base padrão para tudo é um erro comum de conformidade.</p>
</blockquote>
</div>
</section>
<section id="consentimento-de-crianças-e-adolescentes-art.-14" class="slide level2">
<h2>Consentimento de crianças e adolescentes (art. 14)</h2>
<p>O tratamento de dados de <strong>crianças</strong> (até 12 anos incompletos) exige consentimento específico e destacado de pelo menos um dos pais ou responsável legal.</p>
<div class="fragment">
<p>Para <strong>adolescentes</strong> (12 a 18 anos), aplica-se a proteção geral da LGPD, com atenção ao melhor interesse do menor.</p>
</div>
<div class="fragment">
<p>As plataformas devem:</p>
<ul>
<li>realizar esforços razoáveis para verificar a identidade do responsável</li>
<li>manter as informações em formato acessível ao responsável</li>
<li>não condicionar a participação do menor ao fornecimento de dados além dos necessários</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p>A ANPD publicou o <strong>Guia Orientativo: Proteção de Dados Pessoais de Crianças e Adolescentes</strong> com orientações específicas para plataformas digitais, aplicativos e serviços voltados a esse público, incluindo requisitos de design de interfaces e mecanismos de verificação da idade.</p>
</blockquote>
</div>
</section>
<section id="interesse-legítimo-base-legal-mais-complexa-art.-10" class="slide level2 scrollable">
<h2>Interesse legítimo — base legal mais complexa (art. 10)</h2>
<p>O interesse legítimo pode fundamentar o tratamento quando:</p>
<ul>
<li>for necessário para atender aos interesses legítimos do controlador <strong>ou</strong> de terceiro</li>
<li>os interesses legítimos não <strong>prevalecerem</strong> sobre os direitos e liberdades fundamentais do titular</li>
<li>o tratamento não incluir dados sensíveis</li>
</ul>
<div class="fragment">
<p>Um interesse é considerado <strong>legítimo</strong> se atender a três condições:</p>
<ol type="1">
<li>compatibilidade com o ordenamento jurídico</li>
<li>lastro em situações <strong>concretas</strong> (não meramente especulativas)</li>
<li>vinculação a finalidades <strong>específicas e explícitas</strong></li>
</ol>
</div>
</section>
<section id="o-teste-de-balanceamento-3-fases" class="slide level2 smaller">
<h2>O teste de balanceamento — 3 fases</h2>
<p>Segundo o <strong>Guia Orientativo da ANPD (2024)</strong>, o teste possui três fases:</p>
<div class="fragment">
<p><strong>Fase 1 — Finalidade:</strong> identificar o interesse (do controlador ou de terceiro) e avaliar sua legitimidade; verificar se não envolve dados sensíveis; adotar cautelas extras se houver dados de crianças ou adolescentes.</p>
</div>
<div class="fragment">
<p><strong>Fase 2 — Necessidade:</strong> tratar apenas os dados <em>estritamente necessários</em>; verificar se há meios menos intrusivos para atingir a mesma finalidade (art. 10, § 1º).</p>
</div>
<div class="fragment">
<p><strong>Fase 3 — Balanceamento e salvaguardas:</strong> ponderar os interesses do controlador com os direitos e liberdades do titular; adotar salvaguardas proporcionais (ex.: opt-out, prazo reduzido de retenção, controle de acesso).</p>
<blockquote>
<p>O teste deve ser <strong>documentado</strong> — art. 37 exige registro das operações, especialmente quando fundadas no legítimo interesse.</p>
</blockquote>
</div>
</section>
<section id="legítimo-interesse-exemplos-que-podem-ser-válidos" class="slide level2">
<h2>Legítimo interesse — exemplos que podem ser válidos</h2>
<ul>
<li class="fragment"><strong>Universidade envia promoções da própria editora</strong> (livros e produtos culturais) a alunos e professores por e-mail, com mecanismo de descadastramento.</li>
<li class="fragment"><strong>Escola coleta dados de acesso ao wi-fi</strong> para autenticar estudantes e garantir segurança na rede — há relação prévia e finalidade protetiva.</li>
<li class="fragment"><strong>Shopping instala câmeras de segurança</strong>, inclusive para localizar crianças perdidas — desde que com rígido controle de acesso, prazo curto de retenção e sem reconhecimento facial biométrico.</li>
<li class="fragment"><strong>Empresa divulga curso de idiomas de terceiro</strong> a funcionários como incentivo ao aperfeiçoamento profissional, com transparência e opção de recusa.</li>
</ul>
<blockquote>
<p>Em todos os casos o <strong>teste de balanceamento deve ser realizado e documentado</strong>.</p>
</blockquote>
</section>
<section id="legítimo-interesse-quando-não-é-aplicável" class="slide level2">
<h2>Legítimo interesse — quando NÃO é aplicável</h2>
<ul>
<li class="fragment"><strong>Dados sensíveis</strong> (saúde, biometria etc.): a hipótese do art. 10 não abrange dados do art. 11 — exige base legal específica. <em>(Ex.: clínica que alega LI para tratar histórico médico de pacientes.)</em></li>
<li class="fragment"><strong>Publicidade direcionada a crianças</strong> com conteúdo prejudicial <em>(Ex.: app educacional que exibe anúncios de alimentos ultraprocessados a menores — viola o princípio do melhor interesse.)</em></li>
<li class="fragment"><strong>Vigilância total de empregados</strong> <em>(Ex.: software que registra webcam e tudo que é digitado — coleta desproporcional, viola legítima expectativa mesmo que conste na política de privacidade.)</em></li>
<li class="fragment"><strong>Poder Público no exercício de atribuições legais</strong>: deve usar execução de políticas públicas ou cumprimento de obrigação legal — a assimetria de forças impede a ponderação adequada.</li>
</ul>
<blockquote>
<p>O legítimo interesse <strong>não é uma cláusula aberta</strong> para condutas abusivas ou coletas desproporcionais.</p>
</blockquote>
</section>
<section id="bases-legais-para-dados-sensíveis-art.-11" class="slide level2">
<h2>Bases legais para dados sensíveis (art. 11)</h2>
<p>Dados sensíveis só podem ser tratados nas seguintes hipóteses:</p>
<p><strong>Com consentimento:</strong> específico e destacado, para finalidades específicas.</p>
<p><strong>Sem consentimento, quando indispensável para (art. 11, II):</strong></p>
<ul>
<li><strong>a)</strong> cumprimento de obrigação legal ou regulatória</li>
<li><strong>b)</strong> execução de políticas públicas pela administração pública</li>
<li><strong>c)</strong> estudos por órgão de pesquisa (com anonimização sempre que possível)</li>
<li><strong>d)</strong> exercício regular de direitos (inclusive em processo judicial, administrativo ou arbitral)</li>
<li><strong>e)</strong> proteção da vida ou da incolumidade física</li>
<li><strong>f)</strong> tutela da saúde, exclusivamente por profissionais ou autoridades sanitárias</li>
<li><strong>g)</strong> garantia da prevenção à fraude e à segurança do titular (em processos de identificação e autenticação)</li>
</ul>
</section></section>
<section>
<section id="parte-iv-agentes-de-tratamento-e-responsabilidades" class="title-slide slide level1 center">
<h1>Parte IV — Agentes de tratamento e responsabilidades</h1>

</section>
<section id="controlador-art.-5º-vi" class="slide level2">
<h2>Controlador (art. 5º, VI)</h2>
<p>O <strong>controlador</strong> é quem:</p>
<ul>
<li>define <strong>se</strong> o tratamento ocorrerá</li>
<li>define <strong>por que</strong> (finalidade) os dados serão tratados</li>
<li>decide <strong>como</strong> os dados serão usados</li>
<li>determina <strong>quem</strong> terá acesso</li>
</ul>
<div class="fragment">
<p>Pode ser pessoa natural ou jurídica, de direito público ou privado. No setor privado, geralmente é a empresa. No setor público, é o órgão ou entidade pública.</p>
</div>
<div class="fragment">
<blockquote>
<p>O controlador responde pelas decisões tomadas — inclusive pelas decisões de seus operadores.</p>
</blockquote>
</div>
</section>
<section id="operador-art.-5º-vii" class="slide level2">
<h2>Operador (art. 5º, VII)</h2>
<p>O <strong>operador</strong> é quem trata dados <strong>em nome do controlador</strong>, seguindo suas instruções. Exemplos:</p>
<ul>
<li>empresa de computação em nuvem que armazena dados do controlador</li>
<li>empresa de call center contratada para atender clientes</li>
<li>fornecedor de software de CRM que processa dados de clientes do contratante</li>
</ul>
<div class="fragment">
<p>O operador deve observar as instruções do controlador e implementar as medidas de segurança exigidas. Pode ser responsabilizado solidariamente quando descumprir a legislação ou as instruções do controlador.</p>
</div>
</section>
<section id="encarregado-dpo-art.-41" class="slide level2">
<h2>Encarregado (DPO) — art. 41</h2>
<p>O <strong>encarregado pelo tratamento de dados pessoais</strong> (Data Protection Officer — DPO) é a pessoa indicada pelo controlador para:</p>
<ul>
<li>aceitar reclamações e comunicações dos titulares</li>
<li>prestar esclarecimentos e adotar providências</li>
<li>receber comunicações da ANPD</li>
<li>orientar os funcionários e contratados da entidade</li>
<li>executar as demais atribuições determinadas pelo controlador ou estabelecidas em normas complementares</li>
</ul>
<div class="fragment">
<p>A ANPD publicou o <strong>Guia Orientativo sobre a Atuação do Encarregado</strong>, com boas práticas e recomendações detalhadas para o exercício da função.</p>
</div>
</section>
<section id="responsabilidade-e-ressarcimento-arts.-4245" class="slide level2">
<h2>Responsabilidade e ressarcimento (arts. 42–45)</h2>
<p>O <strong>controlador</strong> ou o <strong>operador</strong> que causar dano (material ou moral) ao titular em razão do tratamento são obrigados a repará-lo.</p>
<div class="fragment">
<p><strong>Responsabilidade com inversão do ônus da prova</strong> (art. 43) — o controlador deve demonstrar que não violou a lei, que o dano decorreu de culpa exclusiva do titular ou de terceiro, ou que não realizou o tratamento que lhe é atribuído.</p>
</div>
<div class="fragment">
<p><strong>Excludentes de responsabilidade (art. 43):</strong></p>
<ul>
<li>quando não realizou o tratamento que lhe é atribuído</li>
<li>quando, embora tenha realizado, não houve violação à legislação de proteção de dados</li>
<li>quando o dano é decorrente de culpa exclusiva do titular ou de terceiro</li>
</ul>
</div>
<div class="fragment">
<p>Controlador e operador podem ser <strong>responsabilizados solidariamente</strong> quando o dano decorrer de violação à LGPD.</p>
</div>
</section></section>
<section>
<section id="parte-v-direitos-do-titular" class="title-slide slide level1 center">
<h1>Parte V — Direitos do titular</h1>

</section>
<section id="o-catálogo-de-direitos-do-titular-art.-18" class="slide level2">
<h2>O catálogo de direitos do titular (art. 18)</h2>
<p>O titular tem direito a:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Direito</th>
<th>Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confirmação</strong></td>
<td>saber se existe tratamento de seus dados</td>
</tr>
<tr class="even">
<td><strong>Acesso</strong></td>
<td>obter cópia dos dados tratados</td>
</tr>
<tr class="odd">
<td><strong>Correção</strong></td>
<td>retificar dados incompletos, inexatos ou desatualizados</td>
</tr>
<tr class="even">
<td><strong>Anonimização, bloqueio ou eliminação</strong></td>
<td>para dados desnecessários, excessivos ou tratados em desconformidade</td>
</tr>
<tr class="odd">
<td><strong>Portabilidade</strong></td>
<td>transferência dos dados a outro fornecedor</td>
</tr>
<tr class="even">
<td><strong>Eliminação</strong></td>
<td>dos dados tratados com base no consentimento</td>
</tr>
<tr class="odd">
<td><strong>Informação</strong></td>
<td>sobre os agentes com quem os dados foram compartilhados</td>
</tr>
<tr class="even">
<td><strong>Não consentimento</strong></td>
<td>de ser informado sobre a possibilidade de não fornecer consentimento e sobre as consequências</td>
</tr>
<tr class="odd">
<td><strong>Revogação do consentimento</strong></td>
<td>a qualquer momento, de forma gratuita e facilitada</td>
</tr>
<tr class="even">
<td><strong>Revisão</strong></td>
<td>de decisões tomadas unicamente com base em tratamento automatizado</td>
</tr>
</tbody>
</table>
</section>
<section id="exercício-dos-direitos-pelo-titular" class="slide level2">
<h2>Exercício dos direitos pelo titular</h2>
<p>Os direitos podem ser exercidos:</p>
<ul>
<li>diretamente perante o <strong>controlador</strong>, por requerimento expresso</li>
<li>perante a <strong>ANPD</strong>, por reclamação formal</li>
<li>perante organismos de <strong>defesa do consumidor</strong></li>
</ul>
<div class="fragment">
<p>O controlador deve responder ao titular em prazo determinado pela ANPD (art. 18, §§ 3º e 5º). A resposta pode:</p>
<ul>
<li>atender o pedido</li>
<li>indeferir fundamentadamente (com possibilidade de recurso à ANPD)</li>
</ul>
</div>
</section>
<section id="direito-à-revisão-de-decisões-automatizadas-art.-20" class="slide level2">
<h2>Direito à revisão de decisões automatizadas (art. 20)</h2>
<p>O titular tem direito a solicitar <strong>revisão humana</strong> de decisões tomadas unicamente com base em tratamento automatizado de dados pessoais que afetem seus interesses, incluindo decisões destinadas a definir seu perfil pessoal, profissional, de consumo e de crédito, ou os aspectos de sua personalidade.</p>
<div class="fragment">
<p><strong>Exemplos práticos:</strong></p>
<ul>
<li>negativa de crédito por score automatizado</li>
<li>rejeição de candidatura a emprego por triagem algorítmica</li>
<li>bloqueio de conta em plataforma digital por detecção automática de fraude</li>
</ul>
</div>
<div class="fragment">
<p>O controlador deve informar os critérios e os procedimentos para revisão (art. 20, § 1º). Com a expansão de sistemas de <strong>inteligência artificial</strong>, esse direito ganha crescente relevância — a ANPD acompanha o tema no âmbito do debate sobre regulação de IA no Brasil.</p>
</div>
</section></section>
<section>
<section id="parte-vi-segurança-incidentes-e-boas-práticas" class="title-slide slide level1 center">
<h1>Parte VI — Segurança, incidentes e boas práticas</h1>

</section>
<section id="segurança-da-informação-art.-46" class="slide level2">
<h2>Segurança da informação (art. 46)</h2>
<p>Os agentes de tratamento devem adotar medidas de segurança, técnicas e administrativas, capazes de proteger os dados pessoais de:</p>
<ul>
<li>acessos não autorizados</li>
<li>situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou qualquer forma de tratamento inadequado ou ilícito</li>
</ul>
<div class="fragment">
<p>A ANPD pode dispor sobre padrões técnicos mínimos. Enquanto isso, os agentes devem observar o <strong>estado da técnica</strong> e os princípios gerais da LGPD.</p>
</div>
</section>
<section id="boas-práticas-de-segurança" class="slide level2">
<h2>Boas práticas de segurança</h2>
<p>Com base no <strong>Guia Orientativo da ANPD sobre Segurança da Informação para Agentes de Pequeno Porte</strong>:</p>
<ul>
<li><strong>gestão de acesso:</strong> princípio do menor privilégio — cada usuário acessa apenas o necessário para sua função</li>
<li><strong>senhas e autenticação:</strong> uso de senhas fortes e autenticação em múltiplos fatores</li>
<li><strong>backup:</strong> realização periódica de cópias de segurança em local separado</li>
<li><strong>atualização de sistemas:</strong> aplicação regular de patches e correções de segurança</li>
<li><strong>treinamento:</strong> capacitação dos colaboradores em práticas de segurança</li>
<li><strong>política de descarte:</strong> eliminação segura de dados e dispositivos</li>
</ul>
</section>
<section id="comunicação-de-incidentes-de-segurança-art.-48" class="slide level2">
<h2>Comunicação de incidentes de segurança (art. 48)</h2>
<p>O controlador deve comunicar à <strong>ANPD</strong> e ao <strong>titular</strong> a ocorrência de incidente de segurança que possa acarretar risco ou dano relevante aos titulares.</p>
<div class="fragment">
<p>A comunicação deve ser feita nos <strong>prazos regulamentares</strong> e deve conter:</p>
<ul>
<li>descrição da natureza dos dados afetados</li>
<li>informações sobre os titulares envolvidos</li>
<li>indicação das medidas técnicas e de segurança utilizadas</li>
<li>riscos relacionados ao incidente</li>
<li>medidas adotadas para reverter ou mitigar os efeitos do incidente</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p><strong>Prazos (Resolução CD/ANPD nº 02/2022):</strong> comunicação <strong>preliminar em até 3 dias úteis</strong> e comunicação <strong>complementar em até 20 dias úteis</strong> a partir da ciência do incidente. A ANPD disponibiliza formulário eletrônico próprio (CIS).</p>
</blockquote>
</div>
</section>
<section id="relatório-de-impacto-à-proteção-de-dados-ripd" class="slide level2">
<h2>Relatório de Impacto à Proteção de Dados (RIPD)</h2>
<p>O <strong>RIPD</strong> (art. 38) é um documento elaborado pelo controlador que contém a descrição dos processos de tratamento de dados pessoais que podem gerar riscos às liberdades civis e aos direitos fundamentais, bem como medidas, salvaguardas e mecanismos de mitigação de risco.</p>
<div class="fragment">
<p>A ANPD pode determinar ao controlador a elaboração do RIPD quando o tratamento representar alto risco.</p>
</div>
<div class="fragment">
<p>O RIPD é uma ferramenta de <strong>governança</strong> e <strong>prestação de contas</strong> — materializa o princípio da responsabilização.</p>
</div>
</section>
<section id="privacy-by-design-e-privacy-by-default" class="slide level2">
<h2>Privacy by design e privacy by default</h2>
<p><strong>Privacy by design</strong> (privacidade desde a concepção): - a proteção de dados deve ser considerada desde o projeto de sistemas, produtos e serviços - não é um complemento: é parte integrante do design</p>
<div class="fragment">
<p><strong>Privacy by default</strong> (privacidade como padrão): - as configurações padrão dos sistemas devem ser as mais protetoras da privacidade - o titular não deve precisar agir para ter sua privacidade protegida — o padrão já deve ser o mais restritivo</p>
</div>
<div class="fragment">
<p>Esses conceitos derivam do princípio da prevenção (art. 6º, VIII) e do princípio da necessidade (art. 6º, III).</p>
</div>
</section></section>
<section>
<section id="parte-vii-transferência-internacional-de-dados" class="title-slide slide level1 center">
<h1>Parte VII — Transferência internacional de dados</h1>

</section>
<section id="quando-é-permitida-a-transferência-internacional" class="slide level2">
<h2>Quando é permitida a transferência internacional?</h2>
<p>A transferência de dados pessoais para outros países ou organizações internacionais (art. 33) é permitida quando:</p>
<ul>
<li>o país de destino proporciona <strong>grau de proteção adequado</strong> reconhecido pela ANPD</li>
<li>o controlador oferecer e comprovar <strong>garantias suficientes</strong> (cláusulas contratuais padrão, normas corporativas globais, selos, certificados, códigos de conduta)</li>
<li>a transferência for necessária para <strong>execução de contrato</strong> com o titular</li>
<li>houver <strong>consentimento específico</strong> do titular</li>
<li>for necessária para <strong>cooperação jurídica</strong> entre órgãos públicos</li>
<li>for necessária para <strong>proteção da vida</strong> ou incolumidade física</li>
<li>a ANPD autorizar em casos específicos</li>
</ul>
</section>
<section id="adequabilidade-do-país-receptor" class="slide level2">
<h2>Adequabilidade do país receptor</h2>
<p>A ANPD avalia o nível de proteção de dados do país receptor, considerando:</p>
<ul>
<li>a legislação e normas gerais e setoriais vigentes no país</li>
<li>a natureza dos dados</li>
<li>a observância dos princípios de proteção de dados</li>
<li>a existência de garantias judiciais e institucionais</li>
<li>outras circunstâncias específicas da transferência (art. 34)</li>
</ul>
</section>
<section id="regulamentação-da-anpd-sobre-transferência-internacional" class="slide level2">
<h2>Regulamentação da ANPD sobre transferência internacional</h2>
<p>A <strong>Resolução CD/ANPD nº 19/2023</strong> regulamentou as hipóteses de transferência internacional, estabelecendo:</p>
<ul>
<li><strong>cláusulas contratuais padrão (CCP):</strong> modelo publicado pela ANPD, de uso obrigatório nas contratações com operadores estrangeiros, salvo hipóteses alternativas</li>
<li><strong>normas corporativas globais (BCR):</strong> para grupos empresariais que transferem dados entre suas entidades no exterior, sujeitas a aprovação pela ANPD</li>
<li><strong>avaliação de adequação:</strong> a ANPD publica lista de países e organizações internacionais com proteção considerada adequada</li>
</ul>
<div class="fragment">
<blockquote>
<p>A regulamentação alinha o Brasil ao modelo do GDPR europeu e confere maior segurança jurídica às transferências internacionais.</p>
</blockquote>
</div>
</section></section>
<section>
<section id="parte-viii-anpd-e-o-sistema-de-fiscalização" class="title-slide slide level1 center">
<h1>Parte VIII — ANPD e o sistema de fiscalização</h1>

</section>
<section id="evolução-institucional-da-anpd-20182026" class="slide level2 smaller">
<h2>Evolução institucional da ANPD (2018–2026)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Período</th>
<th>Marco</th>
<th>Natureza jurídica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018–2019</td>
<td>LGPD sancionada; MP 869/2018 e Lei 13.853/2019 criam a ANPD</td>
<td>Órgão da Presidência da República</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Decreto 10.474 — estrutura regimental; nomeação do 1º Diretor-Presidente</td>
<td>Órgão sem autonomia financeira</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>EC 115; MP 1.124 e <strong>Lei 14.460/2022</strong> — transformação em autarquia</td>
<td><strong>Autarquia de natureza especial</strong></td>
</tr>
<tr class="even">
<td>2023</td>
<td>Decretos 11.348 e 11.401 — vinculação ao MJSP</td>
<td>Autarquia vinculada ao MJSP</td>
</tr>
<tr class="odd">
<td>2025</td>
<td>Lei 15.211 (ECA Digital); <strong>MP 1.317</strong> — início da transformação em agência reguladora</td>
<td>Transição</td>
</tr>
<tr class="even">
<td><strong>2026</strong></td>
<td><strong>Lei 15.352/2026</strong> — conversão da MP; Decreto 12.881 — nova estrutura regimental</td>
<td><strong>Agência reguladora</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="anpd-fase-1-criação-20182020" class="slide level2">
<h2>ANPD — Fase 1: criação (2018–2020)</h2>
<p><strong>2018 — Lei nº 13.709 (LGPD):</strong> a lei previa a criação de uma autoridade de proteção de dados, mas não a criou diretamente.</p>
<div class="fragment">
<p><strong>2018 — MP nº 869:</strong> criou a Autoridade Nacional de Proteção de Dados como órgão integrante da Presidência da República, com estrutura mínima (36 cargos).</p>
</div>
<div class="fragment">
<p><strong>2019 — Lei nº 13.853:</strong> converteu a MP e inseriu o desenho institucional definitivo na LGPD — mas a ANPD ainda carecia de autonomia administrativa e financeira.</p>
</div>
<div class="fragment">
<p><strong>2020 — Decreto nº 10.474:</strong> aprovou a primeira estrutura regimental. Em novembro de 2020 foi nomeado o primeiro Diretor-Presidente e a ANPD passou a funcionar efetivamente.</p>
</div>
</section>
<section id="anpd-fase-2-consolidação-como-autarquia-20222024" class="slide level2">
<h2>ANPD — Fase 2: consolidação como autarquia (2022–2024)</h2>
<p><strong>EC nº 115/2022:</strong> elevou a proteção de dados a direito fundamental (art. 5º, LXXIX, CF) e atribuiu à União competência privativa para legislar sobre a matéria.</p>
<div class="fragment">
<p><strong>Lei nº 14.460/2022</strong> (conversão da MP 1.124): transformou a ANPD em <strong>autarquia de natureza especial</strong>, conferindo autonomia técnica, decisória, administrativa, financeira e patrimonial — modelo análogo ao das agências reguladoras.</p>
</div>
<div class="fragment">
<p><strong>2023 — Decretos 11.348 e 11.401:</strong> vincularam a ANPD ao <strong>Ministério da Justiça e Segurança Pública (MJSP)</strong>, com a atribuição de elaborar e coordenar a Política Nacional de Proteção de Dados.</p>
</div>
<div class="fragment">
<p><strong>2024:</strong> intensificação da atividade regulatória — normas sobre incidentes de segurança, transferência internacional, atuação do encarregado e planejamento regulatório.</p>
</div>
</section>
<section id="anpd-fase-3-agência-reguladora-20252026" class="slide level2">
<h2>ANPD — Fase 3: agência reguladora (2025–2026)</h2>
<p><strong>Lei nº 15.211/2025 (ECA Digital):</strong> atribuiu à ANPD novas competências para a proteção de dados de crianças e adolescentes no ambiente digital, incluindo poder de fiscalização sobre plataformas.</p>
<div class="fragment">
<p><strong>MP nº 1.317/2025:</strong> transformou a ANPD em <strong>agência reguladora</strong>, com criação de carreira de estado própria (Carreira de Regulação e Fiscalização de Proteção de Dados).</p>
</div>
<div class="fragment">
<p><strong>Lei nº 15.352/2026</strong> (conversão da MP): criou oficialmente a <strong>Agência Nacional de Proteção de Dados</strong>, inserindo-a no rol das agências reguladoras federais.</p>
</div>
<div class="fragment">
<p><strong>Decreto nº 12.881/2026:</strong> nova estrutura regimental com três superintendências — Fiscalização, Regulação, e Relações Institucionais e Internacionais.</p>
<blockquote>
<p>A transformação em agência reguladora confere à ANPD independência política reforçada, mandatos fixos para os diretores e maior capacidade de enforcement.</p>
</blockquote>
</div>
</section>
<section id="a-anpd-agência-nacional-de-proteção-de-dados" class="slide level2">
<h2>A ANPD — Agência Nacional de Proteção de Dados</h2>
<p>A <strong>ANPD</strong> (Agência Nacional de Proteção de Dados — Lei nº 15.352/2026) é a agência reguladora federal responsável por:</p>
<ul>
<li>zelar pela proteção de dados pessoais</li>
<li>elaborar diretrizes para a <strong>Política Nacional de Proteção de Dados Pessoais e da Privacidade</strong></li>
<li>fiscalizar e aplicar sanções em caso de tratamento irregular</li>
<li>promover o conhecimento sobre proteção de dados na sociedade</li>
<li>estimular boas práticas e a adoção de medidas de governança</li>
<li>proteger dados de <strong>crianças e adolescentes</strong> no ambiente digital (Lei 15.211/2025)</li>
</ul>
<div class="fragment">
<p>Suas competências estão elencadas no art. 55-J da LGPD.</p>
</div>
</section>
<section id="sanções-administrativas-art.-52" class="slide level2">
<h2>Sanções administrativas (art. 52)</h2>
<p>A ANPD pode aplicar as seguintes sanções aos agentes que descumprirem a LGPD:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Sanção</th>
<th>Limite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Advertência</td>
<td>com prazo para adoção de medidas</td>
</tr>
<tr class="even">
<td>Multa simples</td>
<td>até 2% do faturamento (limitada a R$ 50 milhões por infração)</td>
</tr>
<tr class="odd">
<td>Multa diária</td>
<td>com limite total</td>
</tr>
<tr class="even">
<td>Publicização da infração</td>
<td>após apuração e confirmação</td>
</tr>
<tr class="odd">
<td>Bloqueio dos dados</td>
<td>até a regularização</td>
</tr>
<tr class="even">
<td>Eliminação dos dados</td>
<td>relacionados à infração</td>
</tr>
<tr class="odd">
<td>Suspensão parcial do banco de dados</td>
<td>por até 6 meses, prorrogáveis</td>
</tr>
<tr class="even">
<td>Suspensão do tratamento</td>
<td>por até 6 meses, prorrogáveis</td>
</tr>
<tr class="odd">
<td>Proibição parcial ou total do tratamento</td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="critérios-para-dosimetria-das-sanções" class="slide level2">
<h2>Critérios para dosimetria das sanções</h2>
<p>A ANPD considera (art. 52, §1º):</p>
<ul>
<li>a gravidade e a natureza das infrações e dos direitos pessoais afetados</li>
<li>a boa-fé do infrator</li>
<li>a vantagem auferida ou pretendida pelo infrator</li>
<li>a condição econômica do infrator</li>
<li>a reincidência</li>
<li>o grau do dano</li>
<li>a cooperação do infrator com a ANPD</li>
<li>a adoção reiterada e demonstrada de mecanismos e procedimentos de mitigação do impacto dos dados</li>
<li>a adoção de política de boas práticas e governança</li>
<li>a pronta adoção de medidas corretivas</li>
<li>a proporcionalidade entre a gravidade da falta e a intensidade da sanção</li>
</ul>
</section>
<section id="o-cnpd-conselho-nacional-de-proteção-de-dados" class="slide level2">
<h2>O CNPD — Conselho Nacional de Proteção de Dados</h2>
<p>O <strong>CNPD</strong> é órgão consultivo, composto por 23 membros com representação de:</p>
<ul>
<li>poder executivo federal</li>
<li>poder legislativo</li>
<li>poder judiciário e Ministério Público</li>
<li>sociedade civil</li>
<li>instituições científicas, tecnológicas e de inovação</li>
<li>setor empresarial</li>
</ul>
<div class="fragment">
<p>Suas competências incluem propor diretrizes estratégicas e fornecer subsídios para a elaboração da Política Nacional de Proteção de Dados.</p>
</div>
</section></section>
<section>
<section id="parte-ix-tratamento-de-dados-pelo-poder-público" class="title-slide slide level1 center">
<h1>Parte IX — Tratamento de dados pelo poder público</h1>

</section>
<section id="especificidades-do-setor-público-arts.-2332" class="slide level2">
<h2>Especificidades do setor público (arts. 23–32)</h2>
<p>O poder público pode tratar dados pessoais para:</p>
<ul>
<li>execução de <strong>políticas públicas</strong> previstas em leis e regulamentos</li>
<li>cumprimento de <strong>atribuições legais</strong></li>
<li>compartilhamento de dados com outros órgãos, para finalidades específicas e compatíveis</li>
</ul>
<div class="fragment">
<p><strong>Vedação importante (art. 26, §1º):</strong> é proibido ao poder público transferir a entidades privadas dados pessoais constantes de suas bases, salvo exceções expressamente listadas.</p>
</div>
</section>
<section id="princípios-específicos-para-o-poder-público" class="slide level2">
<h2>Princípios específicos para o poder público</h2>
<p>No tratamento de dados pelo setor público:</p>
<ul>
<li>o <strong>controlador</strong> é o órgão ou entidade pública responsável</li>
<li>as finalidades devem ser <strong>públicas e transparentes</strong></li>
<li>deve ser garantido ao cidadão o <strong>acesso às informações</strong> sobre o tratamento, em consonância com a Lei de Acesso à Informação (Lei nº 12.527/2011)</li>
<li>o uso compartilhado de dados entre órgãos deve observar os princípios do art. 6º e ter finalidade específica</li>
</ul>
<div class="fragment">
<blockquote>
<p>A ANPD publicou o <strong>Guia Orientativo para o Tratamento de Dados Pessoais pelo Poder Público</strong>, com orientações específicas para gestores e agentes públicos.</p>
</blockquote>
</div>
</section></section>
<section>
<section id="parte-x-programa-de-governança-em-privacidade" class="title-slide slide level1 center">
<h1>Parte X — Programa de governança em privacidade</h1>

</section>
<section id="o-que-é-um-programa-de-privacidade" class="slide level2">
<h2>O que é um programa de privacidade?</h2>
<p>Um <strong>programa de governança em privacidade</strong> (ou programa de conformidade com a LGPD) é o conjunto estruturado de políticas, processos, controles e treinamentos que uma organização adota para:</p>
<ul>
<li>cumprir as exigências legais da LGPD</li>
<li>demonstrar conformidade à ANPD e aos titulares</li>
<li>prevenir incidentes e reduzir riscos</li>
<li>construir confiança com clientes, parceiros e usuários</li>
</ul>
</section>
<section id="etapas-de-implementação" class="slide level2">
<h2>Etapas de implementação</h2>
<p><strong>1. Mapeamento de dados (data mapping)</strong> Identificar quais dados pessoais a organização trata, onde estão, por quem, para qual finalidade e com qual base legal.</p>
<div class="fragment">
<p><strong>2. Análise de lacunas (gap analysis)</strong> Comparar a situação atual com os requisitos da LGPD e identificar os pontos de não conformidade.</p>
</div>
<div class="fragment">
<p><strong>3. Plano de ação</strong> Definir prioridades, responsáveis e prazos para adequação.</p>
</div>
<div class="fragment">
<p><strong>4. Implementação</strong> Adotar políticas de privacidade, cláusulas contratuais com operadores, controles técnicos e administrativos, treinamentos.</p>
</div>
<div class="fragment">
<p><strong>5. Monitoramento contínuo</strong> Auditorias internas, revisão de políticas, atualização frente a novas regulamentações da ANPD.</p>
</div>
</section>
<section id="inventário-de-dados-o-ponto-de-partida" class="slide level2">
<h2>Inventário de dados: o ponto de partida</h2>
<p>Todo programa começa pelo <strong>inventário de dados</strong> (ou registro das atividades de tratamento), que documenta:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Exemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Categoria de dados</td>
<td>dados cadastrais, dados de saúde, dados financeiros</td>
</tr>
<tr class="even">
<td>Finalidade</td>
<td>concessão de crédito, prestação de serviço</td>
</tr>
<tr class="odd">
<td>Base legal</td>
<td>consentimento, execução de contrato</td>
</tr>
<tr class="even">
<td>Origem</td>
<td>coletado diretamente do titular</td>
</tr>
<tr class="odd">
<td>Compartilhamento</td>
<td>operadores, terceiros</td>
</tr>
<tr class="even">
<td>Retenção</td>
<td>prazo de guarda</td>
</tr>
<tr class="odd">
<td>Medidas de segurança</td>
<td>criptografia, controle de acesso</td>
</tr>
</tbody>
</table>
</section>
<section id="política-de-privacidade-o-que-deve-constar" class="slide level2">
<h2>Política de privacidade: o que deve constar</h2>
<p>A política de privacidade (aviso de privacidade) deve informar:</p>
<ul>
<li>identidade e dados de contato do controlador</li>
<li>dados de contato do encarregado</li>
<li>finalidades do tratamento</li>
<li>bases legais utilizadas</li>
<li>dados pessoais coletados e praticados</li>
<li>compartilhamentos realizados</li>
<li>transferências internacionais (se houver)</li>
<li>prazo de retenção</li>
<li>direitos do titular e como exercê-los</li>
<li>canais de comunicação</li>
</ul>
</section></section>
<section>
<section id="parte-xi-casos-práticos-e-situações-cotidianas" class="title-slide slide level1 center">
<h1>Parte XI — Casos práticos e situações cotidianas</h1>

</section>
<section id="caso-1-cookies-em-sites" class="slide level2">
<h2>Caso 1: cookies em sites</h2>
<p><strong>Situação:</strong> um site coloca cookies de rastreamento nos dispositivos dos visitantes para análise de comportamento e publicidade personalizada.</p>
<div class="fragment">
<p><strong>Análise LGPD:</strong></p>
<ul>
<li>cookies de rastreamento implicam tratamento de dados pessoais</li>
<li>exigem base legal — geralmente <strong>consentimento</strong></li>
<li>o consentimento deve ser <strong>anterior</strong> à colocação dos cookies (não posterior)</li>
<li>o banner de cookies deve oferecer opção <strong>real de recusa</strong> — não apenas um botão “aceitar”</li>
<li>o titular deve poder gerenciar e revogar suas preferências</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p>A ANPD publicou <strong>Guia Orientativo sobre Cookies e Proteção de Dados Pessoais</strong>.</p>
</blockquote>
</div>
</section>
<section id="caso-2-dados-pessoais-no-contexto-trabalhista" class="slide level2">
<h2>Caso 2: dados pessoais no contexto trabalhista</h2>
<p><strong>Situação:</strong> uma empresa coleta dados biométricos (digital) para controle de ponto de funcionários.</p>
<div class="fragment">
<p><strong>Análise LGPD:</strong></p>
<ul>
<li>dados biométricos são <strong>dados sensíveis</strong> (art. 5º, II)</li>
<li>a base legal mais adequada é o <strong>cumprimento de obrigação legal</strong> (CLT permite o controle de jornada) combinado com medidas proporcionais</li>
<li>o empregador deve informar os trabalhadores sobre o tratamento</li>
<li>dados biométricos não devem ser usados para finalidades além do controle de ponto sem nova base legal</li>
<li>medidas de segurança reforçadas são obrigatórias para dados biométricos</li>
</ul>
</div>
</section>
<section id="caso-3-compartilhamento-com-terceiros" class="slide level2">
<h2>Caso 3: compartilhamento com terceiros</h2>
<p><strong>Situação:</strong> uma clínica compartilha dados de saúde de pacientes com um laboratório parceiro para realização de exames.</p>
<div class="fragment">
<p><strong>Análise LGPD:</strong></p>
<ul>
<li>dados de saúde são <strong>sensíveis</strong></li>
<li>o laboratório é um <strong>operador</strong> da clínica para essa finalidade</li>
<li>deve haver <strong>contrato escrito</strong> entre clínica (controladora) e laboratório (operadora), com cláusulas de proteção de dados</li>
<li>o paciente deve ser informado sobre o compartilhamento (transparência)</li>
<li>a base legal pode ser <strong>execução de contrato</strong> com o paciente ou <strong>tutela da saúde</strong></li>
<li>o laboratório só pode usar os dados para a finalidade específica do exame</li>
</ul>
</div>
</section>
<section id="caso-4-vazamento-de-dados" class="slide level2 scrollable">
<h2>Caso 4: vazamento de dados</h2>
<p><strong>Situação:</strong> um e-commerce sofre ataque cibernético e dados de 50.000 clientes (nome, e-mail, CPF e histórico de compras) são expostos.</p>
<div class="fragment">
<p><strong>Obrigações imediatas do controlador:</strong></p>
<ol type="1">
<li><strong>Contenção:</strong> isolar o sistema comprometido, impedir que o vazamento continue</li>
<li><strong>Avaliação:</strong> identificar quais dados foram afetados e quantos titulares</li>
<li><strong>Comunicação à ANPD:</strong> preliminar em <strong>até 3 dias úteis</strong> da ciência; complementar em até 20 dias úteis — via formulário CIS (Resolução CD/ANPD nº 02/2022)</li>
<li><strong>Comunicação aos titulares:</strong> quando o incidente puder acarretar risco ou dano relevante</li>
<li><strong>Medidas corretivas:</strong> implementar controles para prevenir novo incidente</li>
<li><strong>Documentação:</strong> registrar todo o processo de resposta ao incidente</li>
</ol>
</div>
</section>
<section id="caso-5-pesquisa-acadêmica-com-dados-pessoais" class="slide level2">
<h2>Caso 5: pesquisa acadêmica com dados pessoais</h2>
<p><strong>Situação:</strong> uma universidade quer realizar pesquisa sobre hábitos de saúde da população usando dados do sistema de saúde pública.</p>
<div class="fragment">
<p><strong>Análise LGPD:</strong></p>
<ul>
<li>existe base legal específica para <strong>pesquisa por órgão de pesquisa</strong> (art. 7º, IV e art. 11, II, c)</li>
<li>deve ser garantida <strong>anonimização dos dados sempre que possível</strong></li>
<li>os dados só podem ser usados para a finalidade de pesquisa declarada</li>
<li>o compartilhamento com o órgão de pesquisa deve ser formalizado</li>
<li>os resultados da pesquisa não podem permitir a identificação dos titulares</li>
</ul>
<blockquote>
<p>A ANPD publicou <strong>Guia Orientativo para Fins Acadêmicos e Estudos e Pesquisas</strong> com orientações específicas para esse contexto.</p>
</blockquote>
</div>
</section></section>
<section>
<section id="conclusão" class="title-slide slide level1 center">
<h1>Conclusão</h1>

</section>
<section id="síntese-da-aula" class="slide level2">
<h2>Síntese da aula</h2>
<p>Nesta aula percorremos os principais elementos da LGPD:</p>
<ul>
<li><strong>fundamentos:</strong> proteção de dados como direito fundamental</li>
<li><strong>âmbito:</strong> quem a lei alcança e quem ela exclui</li>
<li><strong>conceitos:</strong> dado pessoal, sensível, anonimizado, pseudonimizado</li>
<li><strong>princípios:</strong> os dez mandamentos do art. 6º</li>
<li><strong>bases legais:</strong> as hipóteses lícitas de tratamento</li>
<li><strong>agentes:</strong> controlador, operador, encarregado</li>
<li><strong>direitos dos titulares:</strong> catálogo do art. 18</li>
<li><strong>segurança e incidentes:</strong> obrigações e boas práticas</li>
<li><strong>ANPD:</strong> evolução institucional (2018–2026) e sistema de fiscalização</li>
<li><strong>governança:</strong> como implementar um programa de privacidade</li>
</ul>
<div class="fragment">
<blockquote>
<p>A LGPD não é apenas um conjunto de obrigações — é um <strong>instrumento de construção de confiança</strong> entre organizações e as pessoas cujos dados tratam. Conformidade e ética de dados são, cada vez mais, vantagens competitivas e condição para o exercício legítimo do poder econômico e público na era digital.</p>
</blockquote>
</div>
</section>
<section id="recursos-da-anpd" class="slide level2">
<h2>Recursos da ANPD</h2>
<p>A <strong>ANPD</strong> disponibiliza gratuitamente:</p>
<ul>
<li>Guia sobre atuação do encarregado (DPO)</li>
<li>Guia sobre hipóteses legais — legítimo interesse</li>
<li>Guia para fins acadêmicos e pesquisas</li>
<li>Guia para o poder público</li>
<li>Guia sobre cookies</li>
<li>Guia sobre agentes de tratamento e encarregado</li>
<li>Guia de segurança da informação para pequeno porte</li>
<li>Guia sobre proteção de dados no contexto eleitoral</li>
<li>Fascículos temáticos sobre proteção de dados e vazamentos</li>
<li>Glossário de proteção de dados pessoais e da privacidade</li>
</ul>
<p>Acesso em: <a href="https://www.gov.br/anpd/pt-br/centrais-de-conteudo/materiais-educativos-e-publicacoes">gov.br/anpd</a></p>
</section>
<section id="referências-principais" class="slide level2">
<h2>Referências principais</h2>
<ul>
<li>BRASIL. <strong>Lei nº 13.709, de 14 de agosto de 2018</strong> (Lei Geral de Proteção de Dados Pessoais — LGPD). Brasília: Presidência da República, 2018.</li>
<li>BRASIL. <strong>Lei nº 13.853, de 8 de julho de 2019</strong> (altera a LGPD e cria a ANPD).</li>
<li>BRASIL. <strong>Emenda Constitucional nº 115, de 10 de fevereiro de 2022</strong> (inclui a proteção de dados no art. 5º da CF/88).</li>
<li>ANPD. <strong>Guias Orientativos</strong> (diversas edições). Disponíveis em: gov.br/anpd.</li>
<li>UNIÃO EUROPEIA. <strong>Regulamento (UE) 2016/679</strong> (GDPR). Jornal Oficial da União Europeia, 2016.</li>
</ul>
</section>
<section class="slide level2">

<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Para saber mais</strong></p>
</div>
<div class="callout-content">
<p>Acompanhe as publicações e deliberações da ANPD em <a href="https://www.gov.br/anpd">gov.br/anpd</a> e o portal de dúvidas sobre a LGPD disponível nos canais de atendimento da agência.</p>
</div>
</div>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>LGPD — Lei nº 13.709/2018</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="aula_lgpd_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="aula_lgpd_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="aula_lgpd_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="aula_lgpd_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>