---
title: "Segurança cibernética"
format: revealjs
editor: visual
bibliography: biblio.bib
csl: abnt.csl
---

## Evento cibernético

Evento cibernético é o resultado e um esforço não autorizado, ou o desfecho de vários esforços, arquiteta um efeito primário desejado num alvo[@harry2018classifying].

-   Efeitos primários: impacto direto, e.g., perda de dados.
-   Efeitos secundários: impacto indireto: custos financeiros.

Cibernética: interação da tecnologia, ser humano e organizações.

## Objetivos

-   Disrupção do funcionamento de uma organização.\
    Um invasor pode querer impedir uma organização de oferecer seus serviços e produtos ou de se comunicar com clientes e fornecedores etc.

-   Aquisição ilícita de informação.\
    Um invasor pode querer obter informações sobre cartão de crédito, informações sensíveis etc.

## Eventos disruptivos

-   Manipulação de Mensagens: Interferência na comunicação de dados.
-   Negação de Serviço Externa: Ataques que bloqueiam o acesso ao sistema a partir de fontes externas.
-   Negação de Serviço Interna: Ataques que surgem de dentro da própria rede da organização.
-   Ataque a Dados: Alteração, exclusão, ou corrupção de dados críticos.
-   Ataque Físico: Danos físicos ao hardware ou infraestrutura de TI.

## Eventos de exploração

-   Exploração de Sensores: Captura ou manipulação de dados de sensores.
-   Exploração de Hosts Finais: Ataques direcionados a dispositivos finais, como computadores e servidores.
-   Exploração de Infraestrutura de Rede: Comprometimento de redes para interceptação ou redirecionamento de tráfego.
-   Exploração de Servidor de Aplicações: Vulnerabilidades em servidores que hospedam aplicativos críticos.
-   Exploração de Dados em Trânsito: Interceptação ou manipulação de dados enquanto estão em trânsito na rede.

## Segurança cibernética

### Alocação de recursos, processos e estruturas para proteger redes, sistemas, programas e dados.

## Importância da segurança cibernética

-   Proteção de dados: Seus dados pessoais, como senhas, informações financeiras e dados de saúde, são valiosos para os criminosos cibernéticos. A segurança cibernética ajuda a proteger esses dados de serem roubados ou expostos.
-   Prevenção de interrupções: Ataques cibernéticos podem causar interrupções em serviços essenciais, como bancos, hospitais e redes elétricas. A segurança cibernética ajuda a prevenir esses tipos de interrupções.

## Importância da segurança cibernética

-   Proteção da reputação: Um ataque cibernético pode danificar a reputação de uma empresa ou indivíduo, levando à perda de clientes e confiança.
-   Conformidade com regulamentações: Muitas empresas são obrigadas a cumprir regulamentações de segurança de dados. A segurança cibernética ajuda a garantir que essas regulamentações sejam cumpridas.

## Níveis de questões sobre segurança cibernética

-   Individual

Privacidade

-   Empresarial

Ação de hackers

-   Nacional

Espionagem ou ataques disruptivos

## Principais ameaças cibernéticas

-   Malware: São programas maliciosos, como vírus, worms e ransomware, que podem danificar seus dispositivos e roubar seus dados.
-   Phishing: É uma técnica de engenharia social usada para enganar pessoas a fornecer informações confidenciais, como senhas e números de cartão de crédito.
-   Ataques de negação de serviço (DDoS): São ataques que visam tornar um site ou serviço indisponível, inundando-o com tráfego.
-   Hackers: São pessoas que exploram vulnerabilidades em sistemas para obter acesso não autorizado.
-   Ransomware: É um tipo de malware que criptografa os arquivos de um sistema e exige o pagamento de um resgate para restaurá-los.

## Cookies

Cookies são arquivos instalados no dispositivo de um usuário que per-
mitem a coleta de determinadas informações, inclusive de dados pes-
soais em algumas situações, visando ao atendimento de finalidades
diversas[@lopes2022guia]

## Categorias de cookies
- Entidade responsável
  - Cookies próprios ou primários
  - Cookies de terceiros\
- Necessidade
  - Necessários 
  - Não necessários
  
## Categorias de Cookies
- Finalidade
  - Analíticos ou de desempenho
  - Funcionalidade
  - Publicidade
- Período de retenção
  - temporários
  - persistentes
  
## Bibliografia
