<!DOCTYPE html>
<html lang="pt-BR"><head>
<script src="mci_2026_12_files/libs/clipboard/clipboard.min.js"></script>
<script src="mci_2026_12_files/libs/quarto-html/tabby.min.js"></script>
<script src="mci_2026_12_files/libs/quarto-html/popper.min.js"></script>
<script src="mci_2026_12_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="mci_2026_12_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mci_2026_12_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="mci_2026_12_files/libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="José de Jesus Filho">
  <title>Responsabilidade civil de plataformas digitais no Brasil</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="mci_2026_12_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="mci_2026_12_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="mci_2026_12_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="mci_2026_12_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="mci_2026_12_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="mci_2026_12_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="mci_2026_12_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Responsabilidade civil de plataformas digitais no Brasil</h1>
  <p class="subtitle">MCI, o julgamento do STF (Temas 987/533) e os Decretos nº 12.975 e 12.976/2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
José de Jesus Filho
</div>
</div>
</div>

  <p class="date">18/08/2026</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Roteiro da aula</h2>
<ul>
<li><a href="#/parte-i-fundamentos-e-histórico-normativo" id="/toc-parte-i-fundamentos-e-histórico-normativo">Parte I — Fundamentos e histórico normativo</a></li>
<li><a href="#/parte-ii-o-julgamento-do-stf-temas-987-e-533" id="/toc-parte-ii-o-julgamento-do-stf-temas-987-e-533">Parte II — O julgamento do STF: Temas 987 e 533</a></li>
<li><a href="#/parte-iii-os-novos-decretos-12.975-e-12.9762026" id="/toc-parte-iii-os-novos-decretos-12.975-e-12.9762026">Parte III — Os novos Decretos (12.975 e 12.976/2026)</a></li>
<li><a href="#/parte-iv-perguntas-frequentes-e-o-que-vem-a-seguir" id="/toc-parte-iv-perguntas-frequentes-e-o-que-vem-a-seguir">Parte IV — Perguntas frequentes e o que vem a seguir</a></li>
</ul>
</nav>
</section>
<section>
<section id="parte-i-fundamentos-e-histórico-normativo" class="title-slide slide level1 center">
<h1>Parte I — Fundamentos e histórico normativo</h1>

</section>
<section id="internet-constituição-e-direitos-fundamentais" class="slide level2">
<h2>1. Internet, Constituição e direitos fundamentais</h2>
<ul>
<li>A internet foi consagrada como espaço de comunicação imprescindível à cidadania.</li>
<li>Conflitos típicos: liberdade de expressão × honra, privacidade, dignidade e democracia.</li>
<li>A regulação da responsabilidade de plataformas é peça-chave para proteger bens constitucionais.</li>
</ul>
</section>
<section id="marco-civil-da-internet-estrutura-basilar" class="slide level2">
<h2>2. Marco Civil da Internet — estrutura basilar</h2>
<p><strong>Lei nº 12.965, de 23 de abril de 2014</strong></p>
<ul>
<li>Primeira e principal lei federal sobre governança da internet no Brasil.</li>
<li>Elaborada a partir de amplo processo participativo; tornou-se referência internacional.</li>
</ul>
<div class="fragment">
<p>Entre os princípios do art. 3º:</p>
<ul>
<li>liberdade de expressão;</li>
<li>proteção da privacidade e dos dados pessoais;</li>
<li>neutralidade de rede;</li>
<li>responsabilização dos agentes conforme suas atividades;</li>
<li>estabilidade, segurança e funcionalidade da rede.</li>
</ul>
</div>
</section>
<section id="dois-agentes-centrais" class="slide level2">
<h2>3. Dois agentes centrais</h2>
<p>O MCI destina suas normas de responsabilidade a dois agentes:</p>
<ul>
<li><strong>Provedores de conexão</strong> — simples acesso à internet.</li>
<li><strong>Provedores de aplicações</strong> — disponibilizam um conjunto de funcionalidades acessível por terminal conectado à internet (art. 5º, VII): redes sociais, plataformas de conteúdo, buscadores, mensageria, e-mail.</li>
</ul>
<div class="fragment">
<p>Grande parte dos agentes econômicos do ambiente digital se enquadra na segunda categoria.</p>
</div>
</section>
<section id="provedores-de-conexão-art.-18" class="slide level2">
<h2>4. Provedores de conexão (art. 18)</h2>
<ul>
<li>Não podem ser responsabilizados por danos decorrentes de conteúdo gerado por terceiros.</li>
<li>Simples acesso não implica ingerência no conteúdo.</li>
</ul>
<p>Ponto consolidado na doutrina e na jurisprudência — não foi afetado pelas mudanças recentes.</p>
</section>
<section id="regime-original-do-art.-19-regra-geral" class="slide level2">
<h2>5. Regime original do art. 19 — regra geral</h2>
<blockquote>
<p>“O provedor de aplicações de internet só pode ser responsabilizado civilmente por conteúdo de terceiros se, após <strong>ordem judicial específica</strong>, não remover o conteúdo apontado como infringente dentro do prazo assinalado.”</p>
</blockquote>
<p>Intenção normativa: blindar plataformas de responsabilidade automática, evitar censura privada e deslocar ao Judiciário a análise inicial da ilicitude.</p>
</section>
<section id="exceções-já-previstas-no-texto-original" class="slide level2">
<h2>6. Exceções já previstas no texto original</h2>
<ul>
<li><strong>Art. 21</strong> — dispensa ordem judicial para conteúdo íntimo não consensual (nudez ou atos sexuais de caráter privado), mediante notificação extrajudicial.</li>
<li><strong>Art. 19, §2º e art. 31</strong> — violação de direitos autorais fica sujeita à Lei nº 9.610/1998 (Lei de Direitos Autorais), afastando o regime geral do art. 19.</li>
</ul>
<div class="fragment">
<p>Essa coexistência entre regra geral (art. 19) e exceções (art. 21) foi o centro dos debates que levaram ao julgamento do STF.</p>
</div>
</section>
<section id="decreto-nº-8.7712016-regulamentação-infralegal" class="slide level2">
<h2>7. Decreto nº 8.771/2016 — regulamentação infralegal</h2>
<ul>
<li>Regulamentou o MCI: hipóteses de discriminação de pacotes de dados, guarda e proteção de dados por provedores, transparência na requisição de dados cadastrais e parâmetros de fiscalização.</li>
<li>Atribuiu competências administrativas a órgãos como <strong>Anatel</strong> e <strong>Senacon</strong>.</li>
<li>Segue vigente e é a base sobre a qual o <strong>Decreto nº 12.975/2026</strong> foi construído (Parte III).</li>
</ul>
</section></section>
<section>
<section id="parte-ii-o-julgamento-do-stf-temas-987-e-533" class="title-slide slide level1 center">
<h1>Parte II — O julgamento do STF: Temas 987 e 533</h1>

</section>
<section id="os-casos" class="slide level2">
<h2>8. Os casos</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Tema 987</th>
<th>Tema 533</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leading case</td>
<td>RE nº 1.037.396/SP</td>
<td>RE nº 1.057.258/MG</td>
</tr>
<tr class="even">
<td>Relator</td>
<td>Min. Dias Toffoli</td>
<td>Min. Luiz Fux</td>
</tr>
<tr class="odd">
<td>Questão</td>
<td>Constitucionalidade da exigência de ordem judicial prévia</td>
<td>Regime de responsabilidade dos provedores de aplicações</td>
</tr>
</tbody>
</table>
<p>Julgamento conjunto, concluído em <strong>26 de junho de 2025</strong>.</p>
</section>
<section id="placar-8-a-3" class="slide level2">
<h2>9. Placar: 8 a 3</h2>
<p>O STF, por <strong>maioria de 8 votos a 3</strong>, reconheceu a <strong>inconstitucionalidade parcial e progressiva</strong> do art. 19 do MCI.</p>
<ul>
<li><strong>Maioria</strong>: Dias Toffoli, Luiz Fux, Luís Roberto Barroso, Cristiano Zanin, Flávio Dino, Gilmar Mendes, Alexandre de Moraes e Cármen Lúcia.</li>
<li><strong>Divergência</strong>: André Mendonça, Edson Fachin e Nunes Marques.</li>
</ul>
</section>
<section id="fundamento-da-maioria" class="slide level2">
<h2>10. Fundamento da maioria</h2>
<ul>
<li>A exigência de ordem judicial prévia, em todos os casos, <strong>não protegia adequadamente</strong> bens jurídicos de alta relevância: honra, intimidade, dignidade humana e o regular funcionamento das instituições democráticas.</li>
<li>Era preciso oferecer tutela mais eficiente aos usuários, sobretudo aos que se encontram em condição de vulnerabilidade.</li>
<li>Por isso, fixou-se tese destinada a orientar o regime de responsabilização até que o Congresso edite nova disciplina legislativa.</li>
</ul>
</section>
<section id="divergências-entre-os-ministros" class="slide level2">
<h2>11. Divergências entre os ministros</h2>
<blockquote>
<p>⚠️ Entender as divergências é essencial: elas mostram que a “inconstitucionalidade parcial” não foi consenso técnico, mas uma escolha entre visões distintas sobre como conter dano digital sem abrir espaço a censura privada.</p>
</blockquote>
<div class="fragment">
<p><strong>Min. Edson Fachin</strong> — o art. 19, como estava, era legítimo; não havia omissão inconstitucional a ser suprida pelo STF.</p>
</div>
<div class="fragment">
<p><strong>Min. André Mendonça</strong> — defendeu regulação segmentada, baseada em <strong>diligência devida</strong> do provedor (e não no resultado/conteúdo em si), alertando para o risco de <strong>censura indireta</strong> decorrente de responsabilização mais ampla.</p>
</div>
<div class="fragment">
<p><strong>Min. Nunes Marques</strong> — sustentou que a expressão deve ser tida por inviolável no momento da publicação, cabendo remédios <strong>pós-publicação</strong>; propôs mecanismos internos de “devido processo digital” como alternativa à responsabilização civil ampliada.</p>
</div>
</section>
<section id="a-tese-fixada-regra-geral" class="slide level2">
<h2>12. A tese fixada — regra geral</h2>
<p>Como regra geral, os provedores de aplicações de internet respondem civilmente, <strong>nos termos do art. 21 do MCI</strong>, pelos danos decorrentes de crimes ou atos ilícitos de terceiros quando, <strong>notificados extrajudicialmente</strong>, não removerem o conteúdo.</p>
<div class="fragment">
<p>O regime do art. 21 — antes restrito a conteúdo íntimo não consensual — passou a abranger <strong>crimes e atos ilícitos de naturezas diversas</strong>.</p>
</div>
</section>
<section id="hipóteses-sem-necessidade-de-notificação-prévia" class="slide level2">
<h2>13. Hipóteses sem necessidade de notificação prévia</h2>
<p>A tese previu <strong>duas hipóteses</strong> em que a responsabilização independe de notificação, seja do usuário ou do Judiciário:</p>
<p><strong>1ª hipótese</strong> — presunção relativa de culpa na veiculação de <strong>anúncios e impulsionamentos pagos</strong>, ou em mecanismos artificiais de disseminação inorgânica de conteúdo ilícito (afastável se o provedor comprovar atuação diligente).</p>
</section>
<section id="rol-taxativo-de-crimes-graves" class="slide level2">
<h2>14. Rol taxativo de crimes graves</h2>
<p><strong>2ª hipótese</strong> — dever de cuidado quanto a um <strong>rol taxativo de crimes graves</strong>:</p>
<ul>
<li>atos antidemocráticos;</li>
<li>terrorismo;</li>
<li>indução ao suicídio ou à automutilação;</li>
<li>incitação à discriminação;</li>
<li>crimes praticados contra a mulher em razão do sexo feminino;</li>
<li>crimes sexuais contra vulneráveis;</li>
<li>tráfico de pessoas.</li>
</ul>
<div class="fragment">
<p>Aqui, a responsabilização exige <strong>falha sistêmica</strong> — ausência de medidas adequadas de prevenção ou remoção. A existência isolada de conteúdo ilícito <strong>não basta</strong>.</p>
</div>
</section>
<section id="réplicas-e-contas-inautênticas" class="slide level2">
<h2>15. Réplicas e contas inautênticas</h2>
<ul>
<li>Em republicações de conteúdo cuja ilicitude já foi reconhecida por decisão judicial, os provedores devem remover as publicações <strong>idênticas</strong> mediante notificação, sem necessidade de nova ordem judicial.</li>
<li>A mesma lógica foi estendida a <strong>contas denunciadas como inautênticas</strong> (perfis falsos), dada a facilidade de proliferação desse tipo de conteúdo.</li>
</ul>
</section>
<section id="regime-residual-do-art.-19" class="slide level2">
<h2>16. Regime residual do art. 19</h2>
<p>O regime original — ordem judicial prévia — <strong>permanece válido</strong> para:</p>
<ul>
<li><strong>crimes contra a honra</strong> (difamação, injúria, calúnia), sem prejuízo da remoção por notificação extrajudicial;</li>
<li>serviços de <strong>correio eletrônico</strong>, <strong>reuniões fechadas</strong> por vídeo/voz e <strong>mensageria instantânea</strong>, quanto às comunicações interpessoais protegidas pelo sigilo constitucional das comunicações.</li>
</ul>
</section>
<section id="deveres-complementares-fixados-pelo-stf" class="slide level2">
<h2>17. Deveres complementares fixados pelo STF</h2>
<ul>
<li>deveres de <strong>autorregulação</strong>, <strong>transparência</strong> e <strong>devido processo</strong> na moderação de conteúdo;</li>
<li>exigência de <strong>representante legal no país</strong> para provedores estrangeiros.</li>
</ul>
</section>
<section id="embargos-de-declaração-esclarecimentos" class="slide level2">
<h2>18. Embargos de declaração — esclarecimentos</h2>
<p>Após o julgamento, o STF apreciou embargos de declaração e esclareceu:</p>
<ul>
<li><strong>responsabilidade solidária</strong> entre provedores de aplicação e usuários ofensores;</li>
<li>o art. 19 pode se aplicar também a fornecedores <strong>sem interferência</strong> no fluxo comunicativo/informacional;</li>
<li>o autor de publicação removida pode pedir seu <strong>restabelecimento judicial</strong>, sem que isso implique indenização ao usuário afetado;</li>
<li>responsável e plataforma podem requerer <strong>tutela provisória</strong> para manter o conteúdo até decisão final.</li>
</ul>
</section>
<section id="modulação-de-efeitos-e-prazo" class="slide level2">
<h2>19. Modulação de efeitos e prazo</h2>
<ul>
<li><strong>Modulação prospectiva</strong>: a decisão vale para condutas futuras, preservando situações já decididas.</li>
<li>Prazo de <strong>60 dias</strong>, a contar da publicação da ata do julgamento, para que os provedores implementem os mecanismos necessários ao exercício do dever de cuidado.</li>
<li>Mantido o apelo ao Congresso para legislar sobre a matéria — mas acrescentada a possibilidade de regulamentação pelo <strong>Poder Executivo</strong>.</li>
</ul>
<div class="fragment">
<p>É exatamente essa brecha que os Decretos nº 12.975 e nº 12.976/2026 ocupam.</p>
</div>
</section></section>
<section>
<section id="parte-iii-os-novos-decretos-12.975-e-12.9762026" class="title-slide slide level1 center">
<h1>Parte III — Os novos Decretos (12.975 e 12.976/2026)</h1>

</section>
<section id="contexto-de-edição" class="slide level2">
<h2>20. Contexto de edição</h2>
<ul>
<li>Publicados em <strong>20 de maio de 2026</strong>, com vigência a partir de <strong>20 de julho de 2026</strong> (60 dias após a publicação).</li>
<li>Ambos <strong>atualizam o Decreto nº 8.771/2016</strong>, com base nas teses fixadas nos Temas 987 e 533.</li>
<li>São <strong>autoaplicáveis</strong>: mesmo que venham a ser detalhados por regulamentação da ANPD, isso não impede sua aplicação imediata.</li>
</ul>
</section>
<section id="decreto-nº-12.9752026-panorama" class="slide level2">
<h2>21. Decreto nº 12.975/2026 — panorama</h2>
<p>Insere no Decreto nº 8.771/2016 os arts. <strong>15-A, 16-A a 16-P, 19-A e 20-A</strong>, cobrindo:</p>
<ul>
<li>transparência e guarda de portas lógicas de origem de IP;</li>
<li>obrigações gerais (representante no país, prestação de contas);</li>
<li>dever de cuidado quanto a conteúdo criminoso;</li>
<li>regras procedimentais de indisponibilização de conteúdo;</li>
<li>publicidade abusiva, enganosa ou fraudulenta;</li>
<li>atuação da ANPD e critérios diferenciados por porte/risco.</li>
</ul>
</section>
<section id="conceitos-chave" class="slide level2">
<h2>22. Conceitos-chave</h2>
<blockquote>
<p>⚠️ Estes quatro conceitos são a “gramática” comum dos dois Decretos — vão aparecer o tempo todo na fiscalização da ANPD.</p>
</blockquote>
<ul>
<li><strong>dever de cuidado</strong></li>
<li><strong>falha sistêmica</strong></li>
<li><strong>risco sistêmico</strong></li>
<li><strong>dúvida razoável</strong></li>
</ul>
</section>
<section id="obrigações-gerais-dos-provedores" class="slide level2">
<h2>23. Obrigações gerais dos provedores</h2>
<ul>
<li>Manter <strong>representante legal e sede no país</strong>, com poderes para responder administrativa e judicialmente.</li>
<li>Disponibilizar <strong>canal de denúncia permanente e de fácil acesso</strong> (art. 16-A, II).</li>
<li>Produzir <strong>relatórios de transparência</strong> periódicos.</li>
<li>Adotar <strong>termos de uso</strong> e mecanismos de autorregulação contemplando notificação, devido processo e relatórios anuais.</li>
</ul>
</section>
<section id="publicidade-no-ambiente-digital" class="slide level2">
<h2>24. Publicidade no ambiente digital</h2>
<ul>
<li>Vedação a anúncios e impulsionamentos relacionados a conteúdo criminoso ou ilícito (arts. 16-K a 16-N).</li>
<li>Dever de <strong>guardar dados de anúncios e impulsionamentos por 1 ano</strong> para fins de investigação.</li>
<li>Provedor não é responsabilizado se comprovar atuação diligente.</li>
</ul>
</section>
<section id="devido-processo-de-moderação" class="slide level2">
<h2>25. Devido processo de moderação</h2>
<p>Ao remover (ou manter) um conteúdo notificado, o provedor deve:</p>
<ul>
<li>comunicar a decisão ao denunciante <strong>e</strong> a quem publicou o conteúdo;</li>
<li><strong>justificar</strong> a medida;</li>
<li>informar os <strong>meios de recurso</strong> disponíveis.</li>
</ul>
<div class="fragment">
<p>A avaliação da ilicitude deve considerar o contexto, a liberdade religiosa e de crença, e eventual finalidade informativa, educativa, crítica, satírica ou de paródia (art. 16-G, §2º).</p>
</div>
</section>
<section id="decreto-nº-12.9762026-proteção-da-mulher-online" class="slide level2">
<h2>26. Decreto nº 12.976/2026 — proteção da mulher online</h2>
<p>Trata especificamente da <strong>violência de gênero no ambiente digital</strong>:</p>
<ul>
<li>estabelece princípios orientadores e conceitos (violência psicológica, política, doméstica e familiar digital);</li>
<li>cria sistema integrado de prevenção, proteção e acolhimento;</li>
<li>impõe medidas para <strong>reduzir o alcance</strong> de ataques coordenados contra mulheres;</li>
<li><strong>veda a geração e modificação</strong> de conteúdo íntimo por IA ou qualquer meio tecnológico (deepfakes).</li>
</ul>
</section>
<section id="conteúdo-íntimo-prazo-de-2-horas" class="slide level2">
<h2>27. Conteúdo íntimo — prazo de 2 horas</h2>
<ul>
<li>Remoção de conteúdo íntimo não autorizado em <strong>até 2 horas</strong> após a notificação (art. 7º, §1º).</li>
<li><strong>Bloqueio automático</strong> do reenvio do mesmo material.</li>
<li>Rol próprio de legitimados para notificar: vítima, advogados, autoridades policiais, Ministério Público, Defensorias Públicas.</li>
</ul>
</section>
<section id="o-papel-da-anpd" class="slide level2">
<h2>28. O papel da ANPD</h2>
<ul>
<li>Atribuição conferida pelo art. 19-A do Decreto 12.975/2026 e pelo art. 14 do Decreto 12.976/2026: regulação, fiscalização e apuração de infrações quanto aos deveres dos provedores, nos termos do MCI, da LGPD e do ECA Digital.</li>
</ul>
<div class="fragment">
<blockquote>
<p>⚠️ Ponto central: a ANPD atua de forma <strong>sistêmica e agregada</strong> (mecanismos de supervisão e análise periódica). É <strong>vedado</strong> notificar provedores para moderação de conteúdo isolado, ou responsabilizá-los apenas pela manutenção/remoção de um conteúdo específico.</p>
</blockquote>
</div>
</section>
<section id="convergência-com-lgpd-e-eca-digital" class="slide level2">
<h2>29. Convergência com LGPD e ECA Digital</h2>
<p>A atuação da ANPD nos Decretos dialoga com competências que ela já exerce:</p>
<ul>
<li><strong>LGPD</strong> (art. 55-J, §6º) — já permite análise agregada de reclamações.</li>
<li><strong>ECA Digital</strong> (Lei nº 15.211/2025) — “dever de prevenção” (art. 5º) é próximo ao “dever de cuidado” dos Decretos; deveres de indisponibilização de conteúdo (arts. 27 e 29) espelham os arts. 16-B e 16-G do Decreto 8.771/2016.</li>
</ul>
</section>
<section id="sanções-possíveis" class="slide level2">
<h2>30. Sanções possíveis</h2>
<ul>
<li>Advertência, com prazo para adoção de medidas corretivas.</li>
<li>Multa de até <strong>10% do faturamento</strong> do grupo econômico no Brasil.</li>
<li>Suspensão temporária ou proibição de exercer atividades de tratamento de dados/comunicações.</li>
</ul>
</section></section>
<section>
<section id="parte-iv-perguntas-frequentes-e-o-que-vem-a-seguir" class="title-slide slide level1 center">
<h1>Parte IV — Perguntas frequentes e o que vem a seguir</h1>

</section>
<section id="faq-o-que-é-falha-sistêmica" class="slide level2">
<h2>31. FAQ — o que é “falha sistêmica”?</h2>
<blockquote>
<p>“Ausência de medidas adequadas de prevenção ou remoção de conteúdos ilícitos capazes de inibir sua circulação massiva.”</p>
</blockquote>
<p>A existência <strong>isolada</strong> de um conteúdo ilícito não configura falha sistêmica, se o provedor adotou as medidas preventivas necessárias.</p>
<p><em>(Fonte: FAQ ANPD — Marco Civil da Internet)</em></p>
</section>
<section id="faq-quem-pode-notificar-e-como" class="slide level2">
<h2>32. FAQ — quem pode notificar, e como?</h2>
<ul>
<li>Qualquer pessoa pode notificar conteúdo criminoso, desde que identifique o conteúdo, a ilegalidade e o próprio notificante.</li>
<li>Para conteúdo íntimo não consensual: além da vítima, podem notificar advogados, autoridades policiais, Ministério Público e Defensorias Públicas.</li>
<li>Canal deve ser <strong>permanente e de fácil acesso</strong>.</li>
</ul>
</section>
<section id="faq-as-regras-valem-para-quais-empresas" class="slide level2">
<h2>33. FAQ — as regras valem para quais empresas?</h2>
<ul>
<li>Aplicam-se a provedores de aplicações de internet, sobretudo plataformas de intermediação de conteúdo gerado por usuários.</li>
<li>Geralmente <strong>não se aplicam</strong> a mensageria privada, e-mail ou plataformas de reunião virtual.</li>
<li>Empresas <strong>estrangeiras</strong> que atendem público brasileiro também se submetem (art. 11 do MCI) e devem manter representante legal no país.</li>
</ul>
</section>
<section id="faq-o-que-cabe-denunciar-à-anpd" class="slide level2">
<h2>34. FAQ — o que cabe denunciar à ANPD?</h2>
<ul>
<li>Denuncia-se à ANPD quando a plataforma <strong>não atua de forma proativa e diligente</strong> para inibir a circulação massiva de conteúdo ilícito.</li>
<li>A ANPD avalia a <strong>atuação sistêmica</strong>, não posts específicos — isso continua sendo tarefa do Judiciário (ou da própria plataforma, via canal de denúncia).</li>
</ul>
</section>
<section id="faq-o-que-ainda-poderá-ser-regulamentado" class="slide level2">
<h2>35. FAQ — o que ainda poderá ser regulamentado?</h2>
<p>A ANPD pode editar normas complementares sobre:</p>
<ul>
<li>forma das notificações e prazos de resposta;</li>
<li>procedimentos de contestação e qualificação de notificantes;</li>
<li>relatórios de transparência;</li>
<li>salvaguardas técnicas para identificar e bloquear geração de conteúdo íntimo sintético.</li>
</ul>
</section>
<section id="linha-do-tempo-o-que-vem-a-seguir" class="slide level2">
<h2>36. Linha do tempo — o que vem a seguir</h2>
<ul>
<li><strong>Tomada de Subsídios</strong> (consulta pública) via Plataforma Brasil Participativo, com prazo de 49 dias, a partir da Nota Técnica nº 5/2026/CGTAD/SRE/ANPD.</li>
<li>Atualização dos <strong>Regulamentos de Fiscalização e de Dosimetria</strong> — consulta pública prevista para o 2º semestre de 2026.</li>
<li>Possível inclusão de temas do MCI na <strong>Agenda Regulatória 2027-2028</strong> (também sujeita a consulta social).</li>
</ul>
</section>
<section id="comparação-antes-e-depois" class="slide level2">
<h2>37. Comparação — antes e depois</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Antes (art. 19 original)</th>
<th>Depois (STF + Decretos)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gatilho de responsabilização</td>
<td>Ordem judicial específica</td>
<td>Notificação extrajudicial (regra geral)</td>
</tr>
<tr class="even">
<td>Crimes graves</td>
<td>Exigiam ordem judicial</td>
<td>Dever de cuidado, sem notificação prévia (falha sistêmica)</td>
</tr>
<tr class="odd">
<td>Publicidade paga</td>
<td>Regime geral do art. 19</td>
<td>Presunção relativa de culpa</td>
</tr>
<tr class="even">
<td>Fiscalização</td>
<td>Difusa (Judiciário, caso a caso)</td>
<td>ANPD passa a fiscalizar de forma sistêmica</td>
</tr>
<tr class="odd">
<td>Conteúdo íntimo não consensual</td>
<td>Notificação, sem prazo expresso</td>
<td>Notificação com prazo de 2h (Decreto 12.976)</td>
</tr>
</tbody>
</table>
</section>
<section id="desafios-e-críticas" class="slide level2">
<h2>38. Desafios e críticas</h2>
<ul>
<li>Risco de <strong>overblocking</strong> (remoção excessiva de conteúdo legítimo) por parte de plataformas avessas a risco.</li>
<li>Insegurança jurídica para plataformas de menor porte, ainda que os Decretos prevejam critérios diferenciados por porte/risco (art. 16-P).</li>
<li>Tensão permanente entre eficácia da tutela de direitos e preservação da liberdade de expressão.</li>
<li>Os próprios divergentes do STF (Fachin, Mendonça, Nunes Marques) capturam essas tensões — vale revisitar seus argumentos (slide 11) à luz dos Decretos.</li>
</ul>
</section>
<section id="conclusão" class="slide level2">
<h2>39. Conclusão</h2>
<ul>
<li>A trajetória vai do modelo estático e reativo do art. 19 original a um regime de <strong>responsabilidade qualificada por dever de cuidado</strong>, consolidado pelo STF e detalhado pelos Decretos 12.975 e 12.976/2026.</li>
<li>A ANPD passa a ser peça central de fiscalização — mas de forma <strong>sistêmica</strong>, sem poder de censura sobre conteúdo individual.</li>
<li>Os Decretos <strong>não criam</strong> um regime inteiramente novo: em boa parte, reconstroem deveres que já existiam em outras leis (Código Civil, CDC, ECA Digital), agora unificados sob a ótica do MCI.</li>
<li>O processo de regulamentação continua em aberto — a Tomada de Subsídios e as consultas públicas de 2026 são o próximo capítulo.</li>
</ul>
</section>
<section id="bibliografia" class="slide level2">
<h2>Bibliografia</h2>
<ul>
<li>ANPD. <a href="https://www.gov.br/anpd/pt-br/assuntos/marco-civil-da-internet">Nota Técnica nº 5/2026/CGTAD/SRE/ANPD — Marco Civil da Internet</a>, Processo SEI nº 00261.003483/2026-71.</li>
<li>ANPD. <a href="https://www.gov.br/anpd/pt-br/assuntos/marco-civil-da-internet">Marco Civil da Internet — perguntas frequentes</a></li>
<li>STF. <a href="https://noticias.stf.jus.br/postsnoticias/stf-define-parametros-para-responsabilizacao-de-plataformas-por-conteudos-de-terceiros/">STF define parâmetros para responsabilização de plataformas por conteúdos de terceiros</a> — Temas nº 987 e 533 de Repercussão Geral.</li>
<li><a href="https://drive.google.com/file/d/1tB_6D2jzciNu2TeSYOWORrP_OfY0RS8d/view?usp=sharing">A liberdade de expressão e seus limites: uma análise crítica do marco civil da internet</a></li>
<li>Leitura comparada (citada na Nota Técnica ANPD): <a href="https://eur-lex.europa.eu/legal-content/EN-PT/TXT/?from=EN&amp;uri=CELEX%3A32022R2065">Digital Services Act — União Europeia</a> · <a href="https://www.legislation.gov.uk/ukpga/2023/50/contents">Online Safety Act — Reino Unido</a> · <a href="https://www.legislation.gov.au/C2024A00127/asmade/text">Social Media Minimum Age Act — Austrália</a> </li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Marco Civil da Internet — art. 19 e responsabilidade de plataformas</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="mci_2026_12_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="mci_2026_12_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="mci_2026_12_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="mci_2026_12_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>